import time
print("Hey! I'll be calculating 2 + 2.")
print()
print("=======================")
print("Initializing...")
time.sleep(2.5)
print("Thinking...")
time.sleep(15)
print("Processing...")
time.sleep(15)
print("Computing...")
time.sleep(15)
print("Finalizing...")
time.sleep(2.5)
print("Done!")
print("=======================")
print()
print("Your answer is...")
time.sleep(3)
payment = input("Oops! You have to pay to get the answer. Would you like to pay? ").capitalize()
if payment == "Yes":
	print("Grabbing the answer...")
	time.sleep(5)
	print("The answer is obviously 5.")
else:
	print("Goodbye!")